### ISSUE TITLE
Hello, can i add the Admins / Server from Sourceban?

### ISSUE THREAD

**Issue by Trice1984** [Ferks-FK/SourceAdmin#3]
Hallo,

is there a opinion that i can import Settings from SB 1.8? Admins, Servers?

Many thanks for u

**Comment by Ferks-FK** [comment]
> Hallo,
> 
> is there a opinion that i can import Settings from SB 1.8? Admins, Servers?
> 
> Many thanks for u

Hi, this would be a somewhat complex feature to do, because the DB structures of SourceBans and SourceAdmin are completely different, but it is something to consider in the future.
